import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Para comenzar edite
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentación &rarr;</h2>
            <p>Encuentre información profunda acerca de Next.jsm Características y API</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Aprender &rarr;</h2>
            <p>Aprender acerca de Next.js un curso interactivo con premios!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Ejemplos &rarr;</h2>
            <p>Descubra y despliegue un archivo de ejemplo de proyectos de Next.js.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Desplegar &rarr;</h2>
            <p>Despliegue automáticamente su aplicación de Next.js a una URL pública con Vercel</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Patrocinado por
          <span className={styles.logo}>
            <Image
              className={styles["logo-image"]}
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  )
}
